### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by lysergic57** [k20human/domoticz-linky#2]
Bonjour

J'ai bien renseigné le fichier config.json avec mes identifiants enedis.
Quand j'execute "python3 execute.py" j'obtiens :

pi@raspberrypi ~/linky $ python3 execute.py
2017-10-23 19:12:06,766 :: INFO :: Logging in as xxx@xxx.fr
2017-10-23 19:12:06,772 :: INFO :: Logged in successfully!
2017-10-23 19:12:06,777 :: INFO :: Retreiving data...
2017-10-23 19:12:06,973 :: INFO :: Starting new HTTPS connection (1): espace-client-particuliers.enedis.fr
2017-10-23 19:12:08,022 :: INFO :: Cookie has expired
2017-10-23 19:12:08,052 :: INFO :: Starting new HTTPS connection (1): espace-client-connexion.enedis.fr
2017-10-23 19:12:08,998 :: INFO :: Starting new HTTPS connection (1): espace-client-particuliers.enedis.fr
2017-10-23 19:12:13,236 :: INFO :: Starting new HTTPS connection (1): espace-client-particuliers.enedis.fr
2017-10-23 19:12:14,713 :: INFO :: Got datas!
2017-10-23 19:12:14,753 :: INFO :: Starting new HTTP connection (1): 192.168.0.15
Traceback (most recent call last):
  File "execute.py", line 149, in <module>
    main()
  File "execute.py", line 142, in main
    export_days_values(res_day)
  File "execute.py", line 83, in export_days_values
    'rid': domoticzIdx
TypeError: 'NoneType' object is not callable

Pouvez vous m'aider ?
Quelle version du module request faut il utiliser ?

Merci

**Comment by lysergic57** [comment]
Bonjour

J'ai reussi a solutionner mon probleme en utilisant l'autre fil dans les "Issues"
Désolé, je ne l'avais pas vu n'etant pas familier avec github

En revanche, si mon compteur est maintenant bien incrémenté, il y a un décalge d'un jour dans les données, car nous sommes le 26 et la consommation lue par le script est celle d'hier.

Est ce normal ?

Merci
Nicolas

**Comment by k20human** [comment]
Salut,

Désolé pour le délais de réponse j'ai peu de temps en ce moment ...
Pour le délais d'un jour oui c'est normal car les données du site d'Enedis sont celles de la veille (ce n'est pas du temps réel) alors que l'API de Domoticz se fait en temps réel

**Comment by lysergic57** [comment]
Salut

Pas de soucis.
J'ajoute que pour que le script fonctionne, j'ai du renseigner l'ip du raspberry dans le champ "réseau locaux (pas d'identifiant / mot de passe à fournir )

Nico

**Comment by k20human** [comment]
En théorie si le login / mot de passe est renseigné ça devrait fonctionner mais j'ai moi même utilisé le script en local et j'ai autorisé l'accès à Domoticz sans identifiant donc je n'ai jamais testé le cas login / mot de passe
