### ISSUE TITLE
KeyError: 'Counter'

### ISSUE THREAD

**Issue by kekemar** [k20human/domoticz-linky#3]
Hello,
I have error if execute this script.
Issue : 
Traceback (most recent call last):
  File "./execute.py", line 145, in <module>
    main()
  File "./execute.py", line 138, in main
    export_days_values(res_day)
  File "./execute.py", line 84, in export_days_values
    counterValue = int(float(counter['result'][0]['Counter'].replace(' kWh', '')) * 1000)
KeyError: 'Counter'

Thank's

**Comment by k20human** [comment]
Hi,

I don't use anymore this project :(

**Comment by Xanatos00** [comment]
Try with the original source
https://github.com/outadoc/linkindle
